# Generated by Django 5.2.8 on 2025-11-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Offen'), ('IN_PROGRESS', 'In Bearbeitung'), ('COMPLETED', 'Erledigt')], default='OPEN', max_length=20),
        ),
    ]
