name: Frontend CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: todo-frontend

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              